name: flutter_common_utils
description: Reusable Flutter widgets, extensions, dialogs and UI helpers.
version: 0.0.1
homepage: https://github.com/vladzevun/flutter_common_utils
repository: https://github.com/vladzevun/flutter_common_utils
issue_tracker: https://github.com/vladzevun/flutter_common_utils/issues

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
